### ISSUE TITLE
NameError: name Y is not defined

### ISSUE THREAD

**Issue by samthegitguy** [samthegitguy/timetable#3]
Seems like the new feature with Would You Like To try Again? ( `
Traceback (most recent call last):
    File "timetable.py", line 25, in <module>
        theinput = input("Would you like to try again? (Y/N)
    File "<string>", line 1, in <module>
NameError: Name Y is not defined`)
The variable `theinput` is used to store the result of the input() function.
Seems like the input is taking it as a variable, perhaps I need to use `raw_input()` or `str(input())` perhaps.
Tasklist:

- [x] change to str(input()) or raw_input() 
- [ ] git add
- [ ] git commit
- [ ] git push
- [ ] whatever else is needed.

 

Latest code is in the repo.
@tjsfdc **need your help** if possible.
Got solutions? **drop them in the comments below**

**Comment by samthegitguy** [comment]
So I have tried changing to `raw_input()` and does help, but induces a new error. When I say induced, I mean it gives a new issue, actually.
I used `theinput.lower` to bring the letter case down so that I could compare the input and strings Y/N 
But this gives:
`
NameError: name 'lower' is not defined
`

**Comment by samthegitguy** [comment]
Oh.
I need to use `lower()` not just `.lower`.

**Comment by samthegitguy** [comment]
Problem solved.
